name: Create a release

on:
  pull_request:
    branches: 
      - release/*
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Create a release
        if: github.event.pull_request.merged == true
        run: echo "Creating a release..."; cat README.md